apiVersion: v1
kind: Service
metadata:
  name: oauth-server-service
spec:
  type: NodePort
  selector:
    app: oauth-server
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
      nodePort: 30002

